const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');const {once}=require('node:events');const {createApp}=require('../server');
async function fixture(run,provider){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'hob-support-agent-')),calls=[];const ctx=createApp({dataDir:dir,seedProducts:[{id:'piece',designerId:'maker',title:'Test piece',price:50}],designerTokens:{},resolveIdentity:async({token})=>token==='buyer-a'?{sub:'buyer-a',email:'private-a@example.test'}:token==='buyer-b'?{sub:'buyer-b',email:'private-b@example.test'}:null,houseAiKey:'test-provider-key',houseAiFetch:async(url,request)=>{calls.push(JSON.parse(request.body));return provider(calls.length,JSON.parse(request.body));}});
const now=new Date().toISOString();for(const [id,subject] of [['order-a','buyer-a'],['order-b','buyer-b']]){ctx.db.prepare("INSERT INTO orders(id,buyer_subject,buyer_email,status,currency,subtotal_cents,platform_fee_cents,designer_amount_cents,created_at) VALUES (?,?,?,'paid','usd',5000,500,4500,?)").run(id,subject,subject+'@private.test',now);ctx.db.prepare('INSERT INTO order_items(id,order_id,listing_id,designer_id,title,unit_amount_cents,quantity,line_total_cents,platform_fee_cents,designer_amount_cents) VALUES (?,?,?,?,?,5000,1,5000,500,4500)').run('item-'+id,id,'piece','maker',id==='order-b'?'FOREIGN_PRIVATE_TITLE':'Test piece');}
const server=ctx.app.listen(0,'127.0.0.1');await once(server,'listening');const origin='http://127.0.0.1:'+server.address().port;
const call=async(body={},token='buyer-a')=>{const response=await fetch(origin+'/api/my/support-agent',{method:'POST',headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})},body:JSON.stringify({message:'Where is my order?',consent:true,requestKey:'request_key_123456789',...body})});return{status:response.status,body:await response.json()};};
try{await run({ctx,calls,call});}finally{await new Promise(resolve=>server.close(resolve));ctx.db.close();fs.rmSync(dir,{recursive:true,force:true});}}
const response=output=>({ok:true,json:async()=>({output})});const final=text=>({ok:true,json:async()=>({output_text:text})});const tool=(name,args,id='call_one')=>({type:'function_call',name,arguments:JSON.stringify(args),call_id:id});
test('support requires consent/authentication and tools cannot read another shopper’s order',async()=>fixture(async({ctx,calls,call})=>{
 assert.equal((await call({},'')).status,401);assert.equal((await call({consent:false})).status,422);assert.equal((await call({orderId:'order-b'})).status,404);assert.equal(calls.length,0);
 const result=await call({orderId:'order-a'});assert.equal(result.status,200);assert.ok(result.body.actions.includes('Order and tracking checked'));const encoded=JSON.stringify(calls);assert.equal(encoded.includes('private-a@example.test'),false);assert.equal(encoded.includes('FOREIGN_PRIVATE_TITLE'),false);assert.equal(calls[0].store,false);assert.equal(calls[0].tools.length,2);assert.equal(ctx.db.prepare("SELECT status FROM orders WHERE id='order-a'").get().status,'paid');
},turn=>turn===1?response([tool('lookup_order',{orderId:'order-a'})]):final('Your order is paid. House support can review tracking questions.')));
test('a model-selected foreign order or unsupported financial tool is rejected server-side',async()=>fixture(async({ctx,calls,call})=>{
 const result=await call();assert.equal(result.status,200);assert.equal(JSON.stringify(calls).includes('FOREIGN_PRIVATE_TITLE'),false);assert.equal(JSON.stringify(calls[1]).includes('Order not available in this account'),true);assert.equal(JSON.stringify(calls[1]).includes('This tool is not permitted'),true);assert.equal(ctx.db.prepare('SELECT COUNT(*) n FROM support_messages').get().n,0);assert.equal(ctx.db.prepare("SELECT status FROM orders WHERE id='order-b'").get().status,'paid');
},turn=>turn===1?response([tool('lookup_order',{orderId:'order-b'}),tool('refund_order',{orderId:'order-a'},'call_refund')]):final('Please contact House support for a person to review this.')));
test('escalation needs separate permission and duplicate tool calls/retries create one human ticket',async()=>fixture(async({ctx,calls,call})=>{
 const denied=await call();assert.equal(denied.status,200);assert.equal(denied.body.ticketId,null);assert.equal(ctx.db.prepare('SELECT COUNT(*) n FROM support_messages').get().n,0);
 const body={requestKey:'escalation_key_12345678',orderId:'order-a',allowEscalation:true,message:'My package appears to be missing.'};const allowed=await call(body);assert.equal(allowed.status,200);assert.ok(allowed.body.ticketId);assert.equal(ctx.db.prepare('SELECT COUNT(*) n FROM support_messages').get().n,1);const ticket=ctx.db.prepare('SELECT * FROM support_messages').get();assert.equal(ticket.order_id,'order-a');assert.equal(ticket.buyer_subject,'buyer-a');assert.equal(ticket.status,'open');assert.equal(ticket.message.includes(body.message),true);const before=calls.length;assert.deepEqual((await call(body)).body,allowed.body);assert.equal(calls.length,before);
},turn=>turn%2===1?response([tool('escalate_to_house',{message:'Model summary',category:'shipping'}),tool('escalate_to_house',{message:'Second summary',category:'shipping'},'call_duplicate')]):final('House support can help.')));
test('provider failure after escalation still returns the actual ticket and never claims a refund',async()=>fixture(async({ctx,call})=>{
 const result=await call({allowEscalation:true});assert.equal(result.status,200);assert.ok(result.body.ticketId);assert.equal(result.body.answer.includes('No refund or account change'),true);assert.equal(JSON.stringify(result.body).includes('PROVIDER_SECRET'),false);assert.equal(ctx.db.prepare('SELECT COUNT(*) n FROM support_messages').get().n,1);
},turn=>{if(turn===1)return response([tool('escalate_to_house',{message:'Ask human support',category:'general'})]);throw Error('PROVIDER_SECRET');}));
test('tool loops are bounded and cannot change order state',async()=>fixture(async({ctx,calls,call})=>{const result=await call();assert.equal(result.status,200);assert.equal(calls.length,3);assert.equal(ctx.db.prepare("SELECT status FROM orders WHERE id='order-a'").get().status,'paid');},()=>response([tool('lookup_order',{orderId:'order-a'})])));
