const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),sharp=require('sharp');
const {once}=require('node:events'),{createApp,SELLER_TERMS_VERSION}=require('../server');
async function fixture(run,provider){
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'hob-visual-')),calls=[];
 const ctx=createApp({dataDir:dir,seedProducts:[{id:'piece',designerId:'maker',title:'Botanical skirt',description:'Green floral skirt',price:50},{id:'private',designerId:'maker',title:'PRIVATE_DRAFT',price:60}],designerTokens:{},resolveIdentity:async({token})=>token==='buyer'?{sub:'buyer',email:'secret@example.test'}:null,houseAiKey:'test-key',houseAiFetch:async(url,request)=>{const body=JSON.parse(request.body);calls.push(body);return provider?provider(ctx,body):{ok:true,json:async()=>({output_text:JSON.stringify({matches:[{listingId:'piece',reason:'Similar floral style.'},{listingId:'piece',reason:'Duplicate'}],note:'Style suggestions.'})})};}});
 ctx.db.prepare("UPDATE designer_profiles SET stripe_account_id='acct_test',stripe_payouts_enabled=1,stripe_details_submitted=1,stripe_status_checked_at=CURRENT_TIMESTAMP WHERE id='maker'").run();ctx.db.prepare("UPDATE listings SET status='draft' WHERE id='private'").run();
 ctx.db.prepare('INSERT INTO designer_terms_acceptances (designer_id,terms_version,accepted_at,acceptance_source) VALUES (?,?,?,?)').run('maker',SELLER_TERMS_VERSION,new Date().toISOString(),'test');
 const server=ctx.app.listen(0,'127.0.0.1');await once(server,'listening');const origin='http://127.0.0.1:'+server.address().port;
 const image=await sharp({create:{width:1000,height:800,channels:3,background:'#99bb99'}}).jpeg().withMetadata({exif:{IFD0:{Artist:'PRIVATE_PERSON'}}}).toBuffer();
 async function call({token='buyer',consent='true',bytes=image}={}){const body=new FormData();body.append('image',new Blob([bytes],{type:'image/jpeg'}),'reference.jpg');body.append('consent',consent);const response=await fetch(origin+'/api/my/visual-search',{method:'POST',headers:token?{Authorization:'Bearer '+token}:{},body});return{status:response.status,body:await response.json(),headers:response.headers};}
 try{await run({ctx,calls,call,dir});}finally{await new Promise(resolve=>server.close(resolve));ctx.db.close();fs.rmSync(dir,{recursive:true,force:true});}
}
test('visual search requires auth and consent, strips metadata, grounds IDs and stores no photos',async()=>fixture(async({ctx,calls,call,dir})=>{
 assert.equal((await call({token:''})).status,401);assert.equal((await call({consent:'false'})).status,422);assert.equal((await call({bytes:Buffer.from('invalid')})).status,422);assert.equal(calls.length,0);
 const before=fs.readdirSync(path.join(dir,'images'));const result=await call();assert.equal(result.status,200);assert.equal(result.headers.get('cache-control'),'no-store');assert.equal(result.body.matches.length,1);assert.equal(result.body.matches[0].item.id,'piece');
 const body=calls[0];assert.equal(body.store,false);assert.equal(body.text.format.strict,true);const content=body.input[1].content;assert.equal(content[0].text.includes('PRIVATE_DRAFT'),false);assert.equal(JSON.stringify(body).includes('secret@example.test'),false);
 const encoded=content[1].image_url.split(',')[1],metadata=await sharp(Buffer.from(encoded,'base64')).metadata();assert.equal(metadata.format,'webp');assert.equal(metadata.width,768);assert.equal(metadata.exif,undefined);assert.equal(ctx.db.prepare('SELECT COUNT(*) n FROM listing_images').get().n,0);assert.deepEqual(fs.readdirSync(path.join(dir,'images')),before);
 for(let i=1;i<10;i++)assert.equal((await call()).status,200);assert.equal((await call()).status,429);assert.equal(calls.length,10);
}));
test('availability is rechecked after AI and paused pieces are removed',async()=>fixture(async({call})=>{const result=await call();assert.equal(result.status,200);assert.deepEqual(result.body.matches,[]);},async(ctx)=>{ctx.db.prepare("UPDATE listings SET paused_by_designer=1 WHERE id='piece'").run();return{ok:true,json:async()=>({output_text:JSON.stringify({matches:[{listingId:'piece',reason:'Floral'}],note:'Suggestion'})})};}));
test('invented IDs and provider errors fail safely without leaking provider details',async()=>fixture(async({call})=>{const result=await call();assert.equal(result.status,502);assert.equal(JSON.stringify(result.body).includes('PRIVATE_DRAFT'),false);},async()=>({ok:true,json:async()=>({output_text:JSON.stringify({matches:[{listingId:'private',reason:'PRIVATE_DRAFT'}],note:''})})}))); 
test('vacation and exhausted stock are never sent to the provider',async()=>fixture(async({ctx,calls,call})=>{ctx.db.prepare("UPDATE listings SET stock_quantity=0 WHERE id='piece'").run();assert.deepEqual((await call()).body.matches,[]);assert.equal(calls.length,0);ctx.db.prepare("UPDATE listings SET stock_quantity=1 WHERE id='piece'").run();ctx.db.prepare("UPDATE designer_profiles SET vacation_mode=1 WHERE id='maker'").run();assert.deepEqual((await call()).body.matches,[]);assert.equal(calls.length,0);}));
