import { useState, type FormEvent } from 'react';
import { Link } from 'react-router-dom';
import HouseShell from '@/components/HouseShell';
import { ArrowLeft, ShieldCheck } from '@/lib/icons';

type Operations = {
  summary: { paidOrders:number; pendingOrders:number; heldPayouts:number; failedPayouts:number; releasedPayouts:number; activeReservations:number };
  orders: Array<{id:string;status:string;subtotal_cents:number;platform_fee_cents:number;designer_amount_cents:number;created_at:string;item_count:number;designer_count:number}>;
  payouts: Array<{order_id:string;designer_id:string;amount_cents:number;status:string;error_message?:string;tracking_carrier?:string;tracking_number?:string;tracking_status?:string;release_reason?:string}>;
  inventory: Array<{listing_id:string;order_id:string;status:string;title?:string;designer_id?:string;expires_at:string}>;
};
const money=(c:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format((c||0)/100);

export default function AdminPage(){
  const [token,setToken]=useState(()=>sessionStorage.getItem('hob-admin-token')||'');
  const [data,setData]=useState<Operations|null>(null);
  const [error,setError]=useState('');
  const load=async(e?:FormEvent)=>{e?.preventDefault();setError('');try{const r=await fetch('/api/admin/operations',{headers:{Authorization:`Bearer ${token}`}});const p=await r.json();if(!r.ok)throw new Error(p?.error?.message||'Admin dashboard could not load.');sessionStorage.setItem('hob-admin-token',token);setData(p);}catch(err){setData(null);setError(err instanceof Error?err.message:'Admin dashboard could not load.');}};
  return <HouseShell><main className="mx-auto max-w-7xl px-4 py-12 sm:px-6"><Link to="/" className="inline-flex items-center gap-2 text-sm text-muted-foreground"><ArrowLeft size={16}/> Home</Link><div className="mt-7 flex items-center gap-3"><ShieldCheck className="text-primary"/><div><p className="text-xs font-semibold uppercase tracking-[.2em] text-primary">Private operations</p><h1 className="font-serif text-4xl">House of Briar Admin</h1></div></div>
  {!data&&<form onSubmit={load} className="mt-8 max-w-xl rounded-3xl border border-border bg-card p-6"><label className="text-sm font-medium">Admin access token<input type="password" value={token} onChange={e=>setToken(e.target.value)} className="mt-2 min-h-11 w-full rounded-xl border border-border bg-background px-3"/></label>{error&&<p className="mt-3 text-sm text-destructive">{error}</p>}<button className="mt-5 min-h-11 rounded-full bg-primary px-5 text-sm font-semibold text-primary-foreground">Open dashboard</button></form>}
  {data&&<><div className="mt-8 grid gap-3 sm:grid-cols-2 lg:grid-cols-6">{Object.entries(data.summary).map(([k,v])=><div key={k} className="rounded-2xl border border-border bg-card p-4"><p className="text-2xl font-semibold">{v}</p><p className="mt-1 text-xs uppercase tracking-wide text-muted-foreground">{k.replace(/([A-Z])/g,' $1')}</p></div>)}</div>
  <section className="mt-8 rounded-3xl border border-border bg-card p-6"><h2 className="font-serif text-2xl">Orders</h2><div className="mt-4 overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b border-border text-muted-foreground"><th className="py-3">Order</th><th>Status</th><th>Items</th><th>Total</th><th>Platform 10%</th><th>Designers 90%</th></tr></thead><tbody>{data.orders.map(o=><tr key={o.id} className="border-b border-border/60"><td className="py-3 font-mono text-xs">{o.id.slice(0,10)}</td><td>{o.status}</td><td>{o.item_count}</td><td>{money(o.subtotal_cents)}</td><td>{money(o.platform_fee_cents)}</td><td>{money(o.designer_amount_cents)}</td></tr>)}</tbody></table></div></section>
  <section className="mt-6 rounded-3xl border border-border bg-card p-6"><h2 className="font-serif text-2xl">Payouts & tracking</h2><div className="mt-4 space-y-3">{data.payouts.map((p,i)=><div key={p.order_id+p.designer_id+i} className="rounded-2xl border border-border p-4"><div className="flex flex-wrap justify-between gap-2"><span className="font-medium">{p.designer_id}</span><span>{money(p.amount_cents)} · {p.status}</span></div><p className="mt-2 text-sm text-muted-foreground">Order {p.order_id.slice(0,10)} · {p.tracking_carrier||'No carrier'} {p.tracking_number||''} · {p.tracking_status||'awaiting tracking'}</p>{p.error_message&&<p className="mt-2 text-sm text-destructive">{p.error_message}</p>}</div>)}</div></section>
  <section className="mt-6 rounded-3xl border border-border bg-card p-6"><h2 className="font-serif text-2xl">Inventory holds</h2><div className="mt-4 space-y-2">{data.inventory.map(r=><div key={r.listing_id} className="flex flex-col justify-between gap-1 rounded-xl border border-border p-3 sm:flex-row"><span>{r.title||r.listing_id}</span><span className="text-sm text-muted-foreground">{r.status} · order {r.order_id.slice(0,10)}</span></div>)}</div></section></>}</main></HouseShell>;
}