import { useEffect, useState } from 'react';
import { ArrowUpRight, BadgeCheck, Sparkles } from '@/lib/icons';
import { Link } from 'react-router-dom';
import HouseShell from '@/components/HouseShell';

type Designer={id:string;displayName:string;brandName:string;bio:string;portraitUrl?:string|null;pieceCount:number;soldCount:number;availableCount:number};
export default function DesignersPage(){
 const [designers,setDesigners]=useState<Designer[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState(false);
 useEffect(()=>{let live=true;fetch('/api/designers').then(async r=>{if(!r.ok)throw new Error();return r.json()}).then(d=>{if(live){setDesigners(d.designers??[]);setError(false)}}).catch(()=>{if(live)setError(true)}).finally(()=>{if(live)setLoading(false)});return()=>{live=false}},[]);
 return <HouseShell><section className="mx-auto w-full max-w-7xl px-4 py-16 sm:px-6 lg:px-8"><div className="max-w-2xl"><p className="flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.24em] text-primary"><Sparkles size={15}/> The people behind the pieces</p><h1 className="mt-4 font-serif text-6xl leading-none">Meet the designers.</h1><p className="mt-5 text-lg leading-8 text-muted-foreground">House of Briar is a collection of small worlds, each one shaped by a maker with a point of view.</p></div><section className="mt-10 rounded-3xl border border-border bg-accent/30 p-6 sm:p-8"><p className="text-xs font-semibold uppercase tracking-[0.24em] text-primary">A little house language</p><h2 className="mt-3 font-serif text-3xl">What the badges mean.</h2><div className="mt-6 grid gap-5 sm:grid-cols-2"><div><span className="inline-flex rounded-full bg-accent px-3 py-1 text-xs font-medium text-primary">Founding designer</span><p className="mt-3 text-sm leading-6 text-muted-foreground">One of the first independent makers to help shape House of Briar.</p></div><div><span className="inline-flex items-center gap-1 rounded-full border border-primary/30 bg-primary/10 px-3 py-1 text-xs font-medium text-primary"><BadgeCheck size={14}/> Community donor</span><p className="mt-3 text-sm leading-6 text-muted-foreground">A designer who has chosen to support the marketplace and its creative community.</p></div></div></section>{loading&&<div className="mt-12 h-72 animate-pulse rounded-3xl bg-muted"/>}{!loading&&error&&<p className="mt-12 rounded-3xl border border-dashed border-border p-10 text-center">The designer directory is temporarily unavailable.</p>}{!loading&&!error&&<div className="mt-12 grid gap-6 md:grid-cols-2">{designers.map(d=><article key={d.id} className="rounded-3xl border border-border bg-card p-7 shadow-sm"><div className="flex items-start justify-between gap-4">{d.portraitUrl?<img src={d.portraitUrl} alt={`${d.brandName||d.displayName} portrait`} className="size-20 rounded-full border border-border object-cover"/>:<div className="flex size-20 items-center justify-center rounded-full bg-accent font-serif text-2xl text-primary">{(d.brandName||d.displayName).slice(0,1)}</div>}<span className="rounded-full bg-accent px-3 py-1 text-xs font-medium text-primary">Founding designer</span></div><h2 className="mt-6 font-serif text-3xl">{d.brandName||d.displayName}</h2>{d.bio&&<p className="mt-3 line-clamp-3 text-sm leading-7 text-muted-foreground">{d.bio}</p>}<p className="mt-4 text-xs text-muted-foreground">{d.availableCount} available · {d.soldCount} sold</p><Link to={`/designers/${encodeURIComponent(d.id)}`} className="mt-6 inline-flex min-h-11 items-center gap-2 rounded-full bg-primary px-5 text-sm font-medium text-primary-foreground">Visit their gallery <ArrowUpRight size={16}/></Link></article>)}</div>}</section></HouseShell>;
}