import { useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import HouseShell from '@/components/HouseShell';

type StorefrontItem = { id:string; title:string; price:number; category?:string; images?:Array<{url:string}> };
type Designer = { id:string; displayName:string; brandName:string; bio:string; location:string; productionMethod:string; categories:string[]; portfolioUrl?:string|null; socialUrl?:string|null };

export default function DesignerStorefrontPage() {
  const { designerId } = useParams();
  const [designer,setDesigner]=useState<Designer|null>(null);
  const [items,setItems]=useState<StorefrontItem[]>([]);
  const [loading,setLoading]=useState(true);
  useEffect(()=>{ let live=true; setLoading(true); fetch(`/api/designers/${encodeURIComponent(designerId||'')}`,{headers:{Accept:'application/json'}}).then(async r=>{if(!r.ok)throw new Error('not found');return r.json()}).then(data=>{if(live){setDesigner(data.designer);setItems(Array.isArray(data.items)?data.items:[])}}).catch(()=>{if(live){setDesigner(null);setItems([])}}).finally(()=>{if(live)setLoading(false)}); return()=>{live=false}; },[designerId]);
  if(loading)return <HouseShell><div className="mx-auto max-w-6xl px-4 py-20"><div className="h-12 w-2/3 animate-pulse rounded-2xl bg-muted"/><div className="mt-8 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{[1,2,3].map(i=><div key={i} className="aspect-[4/5] animate-pulse rounded-3xl bg-muted"/>)}</div></div></HouseShell>;
  if(!designer)return <HouseShell><div className="mx-auto max-w-3xl px-4 py-24 text-center"><h1 className="font-serif text-4xl">This designer storefront is unavailable.</h1><p className="mt-3 text-muted-foreground">The shop may be inactive or no longer public.</p><Link to="/shop" className="mt-7 inline-flex min-h-11 items-center rounded-full bg-primary px-5 text-sm font-semibold text-primary-foreground">Browse House of Briar</Link></div></HouseShell>;
  return <HouseShell><main className="mx-auto w-full max-w-7xl px-4 py-12 sm:px-6 lg:px-8"><header className="rounded-[2rem] border border-border bg-card p-7 sm:p-10"><p className="text-xs font-semibold uppercase tracking-[.24em] text-primary">House of Briar designer</p><h1 className="mt-3 font-serif text-5xl sm:text-6xl">{designer.brandName||designer.displayName}</h1>{designer.bio&&<p className="mt-5 max-w-3xl whitespace-pre-wrap text-base leading-8 text-muted-foreground">{designer.bio}</p>}<div className="mt-6 flex flex-wrap gap-2 text-sm">{designer.location&&<span className="rounded-full bg-accent px-3 py-1.5">{designer.location}</span>}{designer.productionMethod&&<span className="rounded-full bg-accent px-3 py-1.5">{designer.productionMethod}</span>}{designer.categories.map(c=><span key={c} className="rounded-full border border-border px-3 py-1.5">{c}</span>)}</div>{(designer.portfolioUrl||designer.socialUrl)&&<div className="mt-6 flex gap-4 text-sm">{designer.portfolioUrl&&<a href={designer.portfolioUrl} target="_blank" rel="noreferrer" className="text-primary hover:underline">Portfolio</a>}{designer.socialUrl&&<a href={designer.socialUrl} target="_blank" rel="noreferrer" className="text-primary hover:underline">Social</a>}</div>}</header><section className="mt-12"><div className="flex items-end justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[.2em] text-primary">Published pieces</p><h2 className="mt-2 font-serif text-3xl">From {designer.brandName||designer.displayName}</h2></div><span className="text-sm text-muted-foreground">{items.length} {items.length===1?'piece':'pieces'}</span></div>{items.length===0?<p className="mt-8 rounded-3xl border border-dashed border-border p-10 text-center text-muted-foreground">No published pieces are available right now.</p>:<div className="mt-7 grid gap-6 sm:grid-cols-2 lg:grid-cols-3">{items.map(item=><Link key={item.id} to={`/shop/${item.id}`} className="group overflow-hidden rounded-3xl border border-border bg-card"><div className="aspect-[4/5] overflow-hidden bg-muted">{item.images?.[0]?.url&&<img src={item.images[0].url} alt={item.title} className="size-full object-cover transition duration-500 group-hover:scale-105"/>}</div><div className="p-5"><p className="text-xs uppercase tracking-wide text-primary">{item.category||'One of one'}</p><div className="mt-2 flex items-start justify-between gap-3"><h3 className="font-serif text-xl">{item.title}</h3><span className="font-semibold">${Number(item.price).toFixed(2)}</span></div></div></Link>)}</div>}</section></main></HouseShell>;
}
