import { useEffect, useState, type FormEvent } from 'react';
import { useAuth } from 'react-oidc-context';

type Note={id:string;note:string;designerReply?:string|null;createdAt:string;verifiedPurchase:boolean};
export default function CollectorNotes({listingId}:{listingId:string}){
 const auth=useAuth();const [notes,setNotes]=useState<Note[]>([]);const [note,setNote]=useState('');const [message,setMessage]=useState('');
 const load=()=>fetch(`/api/listings/${encodeURIComponent(listingId)}/collector-notes`).then(r=>r.json()).then(d=>setNotes(d.notes??[])).catch(()=>{});
 useEffect(()=>{void load();},[listingId]);
 const submit=async(e:FormEvent)=>{e.preventDefault();if(!auth.isAuthenticated){void auth.signinRedirect();return;}setMessage('');const r=await fetch(`/api/listings/${encodeURIComponent(listingId)}/collector-notes`,{method:'POST',headers:{Authorization:`Bearer ${auth.user?.access_token||''}`,'Content-Type':'application/json'},body:JSON.stringify({note})});const d=await r.json().catch(()=>({}));if(!r.ok){setMessage(d?.error?.message||'Collector Note could not be posted.');return;}setNote('');setMessage('Collector Note posted.');void load();};
 return <section><p className="text-xs font-semibold uppercase tracking-[.2em] text-primary">Verified purchase comments</p><h2 className="mt-2 font-serif text-4xl">Collector Notes</h2><p className="mt-3 max-w-2xl text-sm leading-7 text-muted-foreground">No scores or stars—just notes from people who purchased a piece from House of Briar.</p><div className="mt-7 space-y-4">{notes.length===0?<p className="rounded-2xl border border-dashed border-border p-6 text-sm text-muted-foreground">No Collector Notes yet.</p>:notes.map(n=><article key={n.id} className="rounded-2xl border border-border bg-card p-5"><span className="rounded-full bg-accent px-3 py-1 text-xs font-medium text-primary">Verified purchase</span><p className="mt-4 whitespace-pre-wrap text-sm leading-7">{n.note}</p>{n.designerReply&&<div className="mt-4 border-l-2 border-primary/30 pl-4"><p className="text-xs font-semibold uppercase tracking-wide text-primary">Designer reply</p><p className="mt-2 text-sm leading-6">{n.designerReply}</p></div>}</article>)}</div><form onSubmit={submit} className="mt-7 rounded-2xl border border-border bg-card p-5"><label className="text-sm font-medium">Leave a Collector Note<textarea required maxLength={1200} rows={4} value={note} onChange={e=>setNote(e.target.value)} placeholder="Share a note about your purchase…" className="mt-2 w-full rounded-xl border border-border bg-background px-3 py-3"/></label>{message&&<p className="mt-2 text-sm text-primary">{message}</p>}<button type="submit" className="mt-4 min-h-11 rounded-full bg-primary px-5 text-sm font-semibold text-primary-foreground">{auth.isAuthenticated?'Post Collector Note':'Sign in to leave a note'}</button></form></section>;
}