import {useEffect,useRef,useState} from 'react';
type SupportAnswer={answer:string;ticketId:string|null;actions:string[]};
export default function HouseSupportAgent({token}:{token:string}){
 const [message,setMessage]=useState(''),[orderId,setOrderId]=useState(''),[consent,setConsent]=useState(false),[allowEscalation,setAllowEscalation]=useState(false),[busy,setBusy]=useState(false),[answer,setAnswer]=useState<SupportAnswer|null>(null),[error,setError]=useState('');const requestKey=useRef(''),version=useRef(0),controller=useRef<AbortController|null>(null);
 useEffect(()=>{version.current++;controller.current?.abort();requestKey.current='';setMessage('');setOrderId('');setConsent(false);setAllowEscalation(false);setAnswer(null);setError('');setBusy(false);return()=>controller.current?.abort();},[token]);
 function changed(){requestKey.current='';setAnswer(null);setError('');}
 async function ask(){const attempt=++version.current;requestKey.current ||= crypto.randomUUID();controller.current=new AbortController();setBusy(true);setError('');setAnswer(null);try{const response=await fetch('/api/my/support-agent',{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({message,orderId:orderId.trim()||undefined,consent,allowEscalation,requestKey:requestKey.current}),signal:controller.current.signal});const payload=await response.json();if(!response.ok)throw Error(payload.error?.message||'Support could not answer.');if(attempt===version.current)setAnswer(payload);}catch(e){if(attempt===version.current)setError(e instanceof Error?e.message:'Support could not answer.');}finally{if(attempt===version.current)setBusy(false);}}
 return <section id="house-support-agent" className="mb-6 rounded-2xl border border-border p-5"><h3 className="font-serif text-2xl">Ask House support</h3><p className="mt-2 text-sm text-muted-foreground">An AI assistant can check House policies, look up your own order and tracking, and open a ticket for a person to review. Refunds, payouts and account changes require human help.</p><form onSubmit={event=>{event.preventDefault();void ask();}} className="mt-4 space-y-3"><label className="block text-sm">Your question<textarea required minLength={5} maxLength={1500} disabled={busy} value={message} onChange={event=>{setMessage(event.target.value);changed();}} className="mt-2 block w-full rounded-xl border border-border bg-background p-3"/></label><label className="block text-sm">Order reference (optional)<input maxLength={100} disabled={busy} value={orderId} onChange={event=>{setOrderId(event.target.value);changed();}} className="mt-2 block min-h-11 w-full rounded-xl border border-border bg-background px-3"/></label><label className="flex gap-2 text-sm"><input type="checkbox" disabled={busy} checked={consent} onChange={event=>{setConsent(event.target.checked);changed();}}/>Send my question and relevant order summary to OpenAI for support.</label><label className="flex gap-2 text-sm"><input type="checkbox" disabled={busy} checked={allowEscalation} onChange={event=>{setAllowEscalation(event.target.checked);changed();}}/>Allow the assistant to open a House support ticket if human help is needed.</label><button disabled={!token||!consent||busy} className="min-h-11 rounded-full border border-border px-5 text-sm">{busy?'Checking policies and order information…':'Ask House support'}</button></form>{error&&<p role="alert" className="mt-3 text-sm">{error} You can use the support form below.</p>}{answer&&<div role="status" className="mt-4 space-y-3 text-sm"><p className="whitespace-pre-wrap">{answer.answer}</p>{answer.actions.map((action,i)=><p key={i}>✓ {action}</p>)}{answer.ticketId&&<p>Human support ticket: {answer.ticketId}</p>}<p><a href="/rules" className="underline">House rules</a> · <a href="/shipping.html" className="underline">Shipping details</a></p></div>}</section>;
}
