import { useEffect, useState } from 'react';

export type MeasurementProfile={id:string;label:string;bust:string;waist:string;hips:string;height:string;notes:string};
export const MEASUREMENT_PROFILES_KEY='house-of-briar:measurement-profiles';
// Session-only profiles: never persist body measurements in localStorage.
let sessionProfiles: MeasurementProfile[] = [];
export function loadMeasurementProfiles():MeasurementProfile[]{return sessionProfiles.map(p=>({...p}));}
export function clearLegacyMeasurementProfiles(){try{localStorage.removeItem(MEASUREMENT_PROFILES_KEY);}catch{/* storage unavailable */}}
if (typeof window !== 'undefined') clearLegacyMeasurementProfiles();
export default function MeasurementProfiles(){
 const [profiles,setProfiles]=useState<MeasurementProfile[]>([]);
 const [draft,setDraft]=useState<Omit<MeasurementProfile,'id'>>({label:'',bust:'',waist:'',hips:'',height:'',notes:''});
 useEffect(()=>{clearLegacyMeasurementProfiles();setProfiles(loadMeasurementProfiles());},[]);
 const save=()=>{if(!draft.label.trim())return;const next=[...profiles,{...draft,id:crypto.randomUUID()}];sessionProfiles=next;setProfiles(next);setDraft({label:'',bust:'',waist:'',hips:'',height:'',notes:''});window.dispatchEvent(new Event('house-of-briar-measurements'));};
 const remove=(id:string)=>{const next=profiles.filter(p=>p.id!==id);sessionProfiles=next;setProfiles(next);window.dispatchEvent(new Event('house-of-briar-measurements'));};
 return <section className="mb-8 rounded-3xl border border-border bg-card p-6"><p className="text-xs font-semibold uppercase tracking-[0.2em] text-primary">Visitor’s Suite</p><h2 className="mt-2 font-serif text-3xl">Saved measurements</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">Keep more than one fit profile—for yourself, a child, partner, friend, or anyone you shop for. Profiles are kept only in memory while this page is open and are cleared on refresh or when you close the app. Previously saved browser profiles are deleted from this browser. Do not enter measurements on shared devices. Measurements are sent to a designer only when you submit a request for a specific piece.</p><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><input aria-label="Profile name" placeholder="Profile name, e.g. Me or Mom" value={draft.label} onChange={e=>setDraft({...draft,label:e.target.value})} className="min-h-11 rounded-xl border border-border bg-background px-3"/>{(['bust','waist','hips','height'] as const).map(k=><input key={k} aria-label={k} placeholder={k[0].toUpperCase()+k.slice(1)+' (in)'} inputMode="decimal" value={draft[k]} onChange={e=>setDraft({...draft,[k]:e.target.value})} className="min-h-11 rounded-xl border border-border bg-background px-3"/>)}<textarea aria-label="Fit notes" placeholder="Optional fit notes" value={draft.notes} onChange={e=>setDraft({...draft,notes:e.target.value})} className="rounded-xl border border-border bg-background px-3 py-3 sm:col-span-2"/><button type="button" onClick={save} className="min-h-11 rounded-full bg-primary px-5 text-sm font-semibold text-primary-foreground">Save measurement profile</button></div>{profiles.length>0&&<div className="mt-6 grid gap-3 sm:grid-cols-2">{profiles.map(p=><div key={p.id} className="rounded-2xl border border-border p-4"><div className="flex justify-between gap-3"><div><p className="font-medium">{p.label}</p><p className="mt-1 text-xs text-muted-foreground">Bust {p.bust||'—'} · Waist {p.waist||'—'} · Hips {p.hips||'—'} · Height {p.height||'—'}</p>{p.notes&&<p className="mt-2 text-xs text-muted-foreground">{p.notes}</p>}</div><button type="button" onClick={()=>remove(p.id)} className="text-xs text-destructive">Remove</button></div></div>)}</div>}</section>;
}