import { useState, type FormEvent } from 'react';
import { useAuth } from 'react-oidc-context';
import { Send } from '@/lib/icons';

export default function ProductInquiryForm({ productId, productName, designerName }: { productId:string; productName:string; designerName:string }) {
  const auth=useAuth();
  const [message,setMessage]=useState('');
  const [status,setStatus]=useState<'idle'|'sending'|'sent'|'error'>('idle');
  const [error,setError]=useState('');
  const submit=async(event:FormEvent)=>{event.preventDefault();if(!auth.isAuthenticated){void auth.signinRedirect();return;}const trimmed=message.trim();if(trimmed.length<5){setError('Choose a request and add a short item-specific note.');setStatus('error');return;}setStatus('sending');setError('');try{const response=await fetch(`/api/listings/${encodeURIComponent(productId)}/inquiries`,{method:'POST',headers:{Authorization:`Bearer ${auth.user?.access_token||''}`,'Content-Type':'application/json'},body:JSON.stringify({message:trimmed})});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data?.error?.message||'Your message could not be sent.');setMessage('');setStatus('sent');}catch(e){setError(e instanceof Error?e.message:'Your message could not be sent.');setStatus('error');}};
  if(status==='sent')return <div className="rounded-2xl border border-primary/30 bg-accent/40 p-6"><p className="font-serif text-2xl">Sent to {designerName}.</p><p className="mt-2 text-sm text-muted-foreground">The designer can respond Available or Not available. Their response will appear in your account.</p><button type="button" onClick={()=>setStatus('idle')} className="mt-4 min-h-11 rounded-full border border-border px-4 text-sm">Send another request</button></div>;
  return <form onSubmit={submit} className="rounded-2xl border border-border bg-card p-5 sm:p-6"><p className="text-xs font-semibold uppercase tracking-[.2em] text-primary">Request information about this piece</p><h2 className="mt-2 font-serif text-3xl">Ask {designerName} about {productName}</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">This request is attached only to this specific piece. It is not an open chat with the designer.</p><select aria-label="Request type" className="mt-5 min-h-11 w-full rounded-xl border border-border bg-background px-3 text-sm" onChange={e=>setMessage(e.target.value ? `${e.target.value}: ` : "")} defaultValue=""><option value="" disabled>Choose what you need</option><option value="Availability">Availability</option><option value="Similar piece">A similar piece</option><option value="Item details">More item details</option></select><textarea aria-label="Item-specific request" required maxLength={800} rows={4} value={message} onChange={e=>setMessage(e.target.value)} placeholder="Add a short note about this specific piece…" className="mt-5 w-full rounded-xl border border-border bg-background px-3 py-3"/>{status==='error'&&<p role="alert" className="mt-2 text-sm text-destructive">{error}</p>}<button type="submit" disabled={status==='sending'} className="mt-4 inline-flex min-h-12 w-full items-center justify-center gap-2 rounded-full bg-primary px-5 text-sm font-semibold text-primary-foreground disabled:opacity-60"><Send size={16}/>{!auth.isAuthenticated?'Sign in to request':status==='sending'?'Sending…':'Send item request'}</button></form>;
}