import {useEffect,useRef,useState} from 'react';
export type SellerSuggestions={description:string;tags:string[];aesthetic:string;reviewNotes:string[]};
export default function SellerListingAssistant({token,facts,onApply}:{token:string;facts:{title:string;description:string;category:string;style:string;productionType:string};onApply:(suggestions:SellerSuggestions,part:'all'|'description'|'tags'|'aesthetic')=>void}){
  const [consent,setConsent]=useState(false),[busy,setBusy]=useState(false),[suggestions,setSuggestions]=useState<SellerSuggestions|null>(null),[error,setError]=useState('');
  const key=JSON.stringify(facts),version=useRef(0);
  useEffect(()=>{version.current++;setSuggestions(null);},[key,token]);
  async function generate(){const attempt=++version.current;setBusy(true);setError('');setSuggestions(null);try{const response=await fetch('/api/my/studio/assistant',{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({...facts,consent})});const data=await response.json();if(!response.ok)throw Error(data.error?.message||'Suggestions could not load.');if(attempt===version.current)setSuggestions(data);}catch(e){if(attempt===version.current)setError(e instanceof Error?e.message:'Suggestions could not load.');}finally{setBusy(false);}}
  return <section className="my-5 rounded-2xl border border-border p-4"><h3 className="font-serif text-2xl">Automatic seller tools</h3><p className="mt-2 text-sm text-muted-foreground">Turn your factual notes into a description draft, search tags and an aesthetic. Review before saving; suggestions never publish a listing.</p><label className="mt-3 flex gap-2 text-sm"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/>Send these listing details to OpenAI for suggestions.</label><button type="button" onClick={()=>void generate()} disabled={busy||!consent||!facts.title.trim()} className="mt-3 min-h-11 rounded-full border border-border px-4 text-sm">{busy?'Creating suggestions…':'Generate description, tags & aesthetic'}</button>{error&&<p role="alert" className="mt-3 text-sm">{error}</p>}{suggestions&&<div className="mt-4 space-y-3 text-sm"><p className="whitespace-pre-wrap">{suggestions.description}</p><p><strong>Suggested tags:</strong> {suggestions.tags.join(', ')}</p><p><strong>Suggested aesthetic:</strong> {suggestions.aesthetic}</p>{suggestions.reviewNotes.map((note,i)=><p key={i} className="text-muted-foreground">{note}</p>)}<p>Check materials, condition and fit claims against the actual piece.</p><div className="flex flex-wrap gap-2">{(['all','description','tags','aesthetic'] as const).map(part=><button type="button" key={part} className="min-h-11 rounded-full border border-border px-4" onClick={()=>onApply(suggestions,part)}>{part==='all'?'Use all suggestions':`Use ${part}`}</button>)}</div></div>}</section>;
}
