import { useEffect, useState, useRef } from 'react';
export const LISTING_STATUSES=['Active','Draft','Expired','Sold Out','Inactive'] as const;
export type ListingStatus=typeof LISTING_STATUSES[number];
export type StudioSummary={ordersCount:number;counts:Record<ListingStatus,number>;views:{events:number;sessions:number;days:number};orders:Array<{id:string;status:string;title:string;quantity:number}>;messages:number;items:Array<{id:string;title:string;studioStatus:ListingStatus}>};
export function ListingStatusTabs({counts,selected,onSelect}:{counts:Record<ListingStatus,number>;selected:string;onSelect:(status:string)=>void}){
  return <section aria-label="Listing status" className="mt-6"><h2 className="font-serif text-2xl">Listing status</h2><div className="mt-3 flex flex-wrap gap-2">{['All',...LISTING_STATUSES].map(status=><button type="button" key={status} aria-pressed={selected===status} onClick={()=>onSelect(status)} className={`min-h-11 rounded-xl border border-border px-4 text-sm ${selected===status?'bg-primary text-primary-foreground':'bg-card'}`}>{status} <strong>{status==='All'?Object.values(counts).reduce((a,b)=>a+b,0):counts[status as ListingStatus]}</strong></button>)}</div><p role="status" className="mt-3 text-sm text-muted-foreground">{selected==='All'?'Showing all listings.':`Listings have been updated to display only ${selected.toLowerCase()} listings.`}</p></section>;
}
export function StudioDashboard({summary,selected,onSelect}:{summary:StudioSummary|null;selected:string;onSelect:(status:string)=>void}){
  if(!summary)return <p role="status">Loading studio overview…</p>;
  return <section id="studio-overview" className="my-8 rounded-3xl border border-border bg-card p-6"><h2 className="font-serif text-3xl">Your studio at a glance</h2><nav className="mt-4 flex flex-wrap gap-4 text-sm"><a href="#orders" className="underline">Orders ({summary.ordersCount})</a><a href="#designer-item-requests" className="underline">Item requests ({summary.messages})</a><a href="#messages" className="underline">Messages &amp; alerts</a><a href="#shared-access" className="underline">Shared access</a></nav><p className="mt-4 text-sm">Views in the last {summary.views.days} days: <strong>{summary.views.events}</strong> · {summary.views.sessions} browsing sessions</p><p className="mt-1 text-xs text-muted-foreground">Views are tracked product-page events, not verified people; browsers that block tracking may not be counted.</p><ListingStatusTabs counts={summary.counts} selected={selected} onSelect={onSelect}/></section>;
}
export function SharedStudioAccess({token}:{token:string}){
  const [data,setData]=useState<{members:Array<{id:string;name:string;email:string}>;studios:Array<{id:string;name:string}>}>({members:[],studios:[]});
  const selection=useRef(0);
  const [email,setEmail]=useState(''),[message,setMessage]=useState(''),[shared,setShared]=useState<StudioSummary|null>(null),[busy,setBusy]=useState(false);
  async function api(path:string,method='GET',body?:object){const r=await fetch(path,{method,headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});const payload=await r.json();if(!r.ok)throw new Error(payload.error?.message||'Studio access could not load.');return payload;}
  async function refresh(){setData(await api('/api/my/studio/shared-access'));}
  useEffect(()=>{let active=true;setShared(null);selection.current++;setData({members:[],studios:[]});void api('/api/my/studio/shared-access').then(d=>{if(active)setData(d);}).catch(e=>{if(active)setMessage(e.message);});return()=>{active=false;};},[token]);
  async function change(method:string,id?:string){setBusy(true);setMessage('');try{await api('/api/my/studio/shared-access'+(id?'/'+encodeURIComponent(id):''),method,method==='POST'?{email}:undefined);setEmail('');await refresh();setMessage(method==='POST'?'Read-only studio access granted.':'Access revoked.');}catch(e){setMessage(e instanceof Error?e.message:'Access could not be changed.');}finally{setBusy(false);}}
  return <section id="shared-access" className="my-8 rounded-3xl border border-border bg-card p-6"><h2 className="font-serif text-2xl">Shared access</h2><p className="mt-2 text-sm text-muted-foreground">Let a helper view listing status, order summaries, request counts and views through their own verified designer account. Access is read-only. Buyer addresses, notes, message content, payout settings and editing stay private. You can revoke access at any time.</p><form className="mt-4 flex flex-wrap gap-3" onSubmit={e=>{e.preventDefault();void change('POST');}}><input type="email" required maxLength={254} aria-label="Helper’s verified House email" placeholder="Helper’s verified House email" value={email} onChange={e=>setEmail(e.target.value)} className="min-h-11 rounded-xl border border-border bg-background px-3"/><button disabled={busy} className="min-h-11 rounded-full bg-primary px-5 text-primary-foreground">Grant read-only access</button></form>{message&&<p role="status" className="mt-3 text-sm">{message}</p>}<ul className="mt-4 space-y-3">{data.members.map(member=><li key={member.id} className="flex flex-wrap items-center gap-4 text-sm">{member.name||member.email} · {member.email}<button type="button" disabled={busy} className="underline" onClick={()=>void change('DELETE',member.id)}>Revoke access</button></li>)}</ul>{data.studios.length>0&&<><label className="mt-6 block text-sm">Studios shared with you<select defaultValue="" className="ml-3 min-h-11 rounded-xl border border-border bg-background px-3" onChange={e=>{const id=e.target.value,version=++selection.current;setShared(null);if(id)void api('/api/my/studio/shared/'+encodeURIComponent(id)).then(data=>{if(version===selection.current)setShared(data);}).catch(error=>{if(version===selection.current)setMessage(error.message);});}}><option value="">Choose a shared studio</option>{data.studios.map(studio=><option key={studio.id} value={studio.id}>{studio.name||studio.id}</option>)}</select></label>{shared&&<div className="mt-4 rounded-xl border border-border p-4"><h3 className="font-semibold">Shared studio · read-only</h3><p className="mt-2 text-sm">{shared.views.events} views · {shared.messages} item requests</p><ul className="mt-3 space-y-2 text-sm">{shared.items.map(item=><li key={item.id}>{item.title} — {item.studioStatus}</li>)}</ul><h4 className="mt-4 font-semibold">Recent order items</h4><ul className="mt-2 text-sm">{shared.orders.map((order,i)=><li key={`${order.id}-${i}`}>{order.id.slice(0,8)} · {order.title} × {order.quantity} · {order.status}</li>)}</ul></div>}</>}</section>;
}
