import {useEffect,useRef,useState} from 'react';
import {Link} from 'react-router-dom';
type Match={item:{id:string;title:string;price:number;imageUrl:string|null};reason:string};
export default function VisualSearch({token}:{token:string}) {
 const [file,setFile]=useState<File|null>(null),[preview,setPreview]=useState(''),[consent,setConsent]=useState(false),[busy,setBusy]=useState(false),[matches,setMatches]=useState<Match[]>([]),[note,setNote]=useState(''),[error,setError]=useState('');
 const version=useRef(0),controller=useRef<AbortController|null>(null),picker=useRef<HTMLInputElement>(null);
 function clear(){version.current++;controller.current?.abort();setFile(null);setConsent(false);setMatches([]);setNote('');setError('');setBusy(false);if(picker.current)picker.current.value='';}
 useEffect(()=>{clear();return()=>{version.current++;controller.current?.abort();};},[token]);
 useEffect(()=>{if(!file){setPreview('');return;}const url=URL.createObjectURL(file);setPreview(url);return()=>URL.revokeObjectURL(url);},[file]);
 async function search(){if(!file||!consent)return;const attempt=++version.current;controller.current?.abort();controller.current=new AbortController();setBusy(true);setError('');setMatches([]);setNote('');const body=new FormData();body.append('image',file);body.append('consent','true');try{const response=await fetch('/api/my/visual-search',{method:'POST',headers:{Authorization:`Bearer ${token}`},body,signal:controller.current.signal});const result=await response.json();if(!response.ok)throw Error(result.error?.message||'Photo search could not complete.');if(attempt===version.current){setMatches(result.matches);setNote(result.note||(!result.matches.length?'No similar pieces found. Try another photo or text search.':''));}}catch(e){if(attempt===version.current)setError(e instanceof Error?e.message:'Photo search could not complete.');}finally{if(attempt===version.current)setBusy(false);}}
 return <section aria-labelledby="visual-search-title" className="mt-8 min-w-0 rounded-2xl border border-border bg-card p-5"><h2 id="visual-search-title" className="font-serif text-2xl">Find pieces from a photo</h2><p className="mt-2 text-sm text-muted-foreground">Find style similarities in a selection of available House pieces using your photo and catalog descriptions. Results are suggestions; exact matches and fit are not guaranteed.</p><p className="mt-2 text-sm text-muted-foreground">Your photo stays on your device until you search. House strips image metadata and reduces its size before sending it to OpenAI. House does not save the search photo. OpenAI processing is subject to its data policies.</p>{!token&&<p className="mt-3 text-sm"><Link to="/account" className="underline">Sign in</Link> to use photo search, or use text search below.</p>}<form onSubmit={event=>{event.preventDefault();void search();}} className="mt-4 space-y-3"><label className="block text-sm">Reference photo<input ref={picker} type="file" accept="image/jpeg,image/png,image/webp,image/avif,image/heic" disabled={!token||busy} onChange={event=>{const selected=event.target.files?.[0]||null;clear();if(selected&&selected.size>10*1024*1024){setError('Choose a photo under 10 MB.');return;}setFile(selected);}} className="mt-2 block min-h-11 w-full min-w-0 text-sm"/></label>{preview&&<img src={preview} alt="Your selected reference" className="max-h-48 max-w-full rounded-xl object-contain"/>}<label className="flex gap-2 text-sm"><input type="checkbox" checked={consent} disabled={!token||busy} onChange={event=>setConsent(event.target.checked)}/>Send this photo to OpenAI to find similar House pieces.</label><div className="flex flex-wrap gap-3"><button disabled={!token||!file||!consent||busy} className="min-h-11 rounded-full border border-border px-5 text-sm">{busy?'Finding similar pieces…':'Search from photo'}</button><button type="button" onClick={clear} className="min-h-11 rounded-full border border-border px-5 text-sm">Clear photo and results</button></div></form>{error&&<p role="alert" className="mt-3 text-sm">{error}</p>}<div role="status" className="mt-3 text-sm">{note}</div><div className="mt-4 grid min-w-0 gap-4 sm:grid-cols-2 lg:grid-cols-3">{matches.map(match=><Link key={match.item.id} to={`/shop/${encodeURIComponent(match.item.id)}`} className="min-w-0 rounded-xl border border-border p-4">{match.item.imageUrl&&<img src={match.item.imageUrl} alt={match.item.title} className="mb-3 aspect-square w-full rounded-lg object-cover"/>}<h3 className="font-medium">{match.item.title}</h3><p className="mt-1 text-sm">${match.item.price.toFixed(2)}</p><p className="mt-2 text-sm text-muted-foreground">{match.reason}</p></Link>)}</div></section>;
}
